name: file_manger
description: "file_manger"
version: 1.0.0+1

environment:
  sdk: ^3.8.1
  flutter: ">=3.23.3"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  core: any
  updater: any
  get: ^4.7.2
  path_provider: ^2.1.5
  realm: ^20.1.1
  path: ^1.9.0
  get_it: ^8.0.3
  google_fonts: ^6.2.1
  flex_color_scheme: ^8.2.0
  webdav_client: ^1.2.2
  window_manager: ^0.5.0
  lucide_icons_flutter: ^3.0.5
  flutter_breadcrumb: ^1.0.1
  dartx: ^1.2.0
  fvp: ^0.32.1
  video_player: ^2.10.0
  flick_video_player: ^0.9.0
  flutter_staggered_grid_view: ^0.7.0
  media_kit: any
  media_kit_video: any
  media_kit_libs_video: any

dependency_overrides:
  core:
    path: ./packages/core
  updater:
    path: ./packages/updater
  media_kit:
    git:
      url: https://github.com/Predidit/media-kit.git
      ref: main
      path: ./media_kit
  media_kit_video:
    git:
      url: https://github.com/Predidit/media-kit.git
      ref: main
      path: ./media_kit_video
  media_kit_libs_video:
    git:
      url: https://github.com/Predidit/media-kit.git
      ref: main
      path: ./libs/universal/media_kit_libs_video
  media_kit_libs_linux:
    git:
      url: https://github.com/Predidit/media-kit.git
      ref: main
      path: ./libs/linux/media_kit_libs_linux
  media_kit_libs_ios_video:
    git:
      url: https://github.com/Predidit/media-kit.git
      ref: main
      path: ./libs/ios/media_kit_libs_ios_video
  media_kit_libs_android_video:
    git:
      url: https://github.com/Predidit/media-kit.git
      ref: main
      path: ./libs/android/media_kit_libs_android_video
  media_kit_libs_windows_video:
    git:
      url: https://github.com/Predidit/media-kit.git
      ref: main
      path: ./libs/windows/media_kit_libs_windows_video
  media_kit_libs_macos_video:
    git:
      url: https://github.com/Predidit/media-kit.git
      ref: main
      path: ./libs/macos/media_kit_libs_macos_video

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/locales/
    - assets/shaders/
